import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Pixelify_Sans } from "next/font/google";
import "./globals.css";
import RootHeader from "@/components/marketing/root-header";
import { ThemeProvider } from "@/components/common/theme-provider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const pixelifySans = Pixelify_Sans({
  variable: "--font-pixelify-sans",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.className} ${pixelifySans.variable} antialiased h-screen overflow-y-auto`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <RootHeader />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
